logger:
  file: /open5gs/install/var/log/open5gs/ausf.log

sbi:
  server:
    no_tls: true
    cacert: /open5gs/install/etc/open5gs/tls/ca.crt
    key: /open5gs/install/etc/open5gs/tls/ausf.key
    cert: /open5gs/install/etc/open5gs/tls/ausf.crt
  client:
    no_tls: true
    cacert: /open5gs/install/etc/open5gs/tls/ca.crt
    key: /open5gs/install/etc/open5gs/tls/ausf.key
    cert: /open5gs/install/etc/open5gs/tls/ausf.crt

ausf:
  sbi:
    - addr: 127.0.0.11
      port: 7777

scp:
  sbi:
    - addr: 127.0.1.10
      port: 7777