logger:
  file: /open5gs/install/var/log/open5gs/nssf.log

sbi:
  server:
    no_tls: true
    cacert: /open5gs/install/etc/open5gs/tls/ca.crt
    key: /open5gs/install/etc/open5gs/tls/nssf.key
    cert: /open5gs/install/etc/open5gs/tls/nssf.crt
  client:
    no_tls: true
    cacert: /open5gs/install/etc/open5gs/tls/ca.crt
    key: /open5gs/install/etc/open5gs/tls/nssf.key
    cert: /open5gs/install/etc/open5gs/tls/nssf.crt

nssf:
  sbi:
    - addr: 127.0.0.14
      port: 80
  nsi:
    - addr: 127.0.0.10
      port: 7777
      s_nssai:
        sst: 1
        sd: 000001
    - addr: 127.0.0.10
      port: 7777
      s_nssai:
        sst: 2
        sd: 000002
      
scp:
  sbi:
    - addr: 127.0.1.10
      port: 7777