db_uri: mongodb://mongodb/open5gs

logger:
  file: /open5gs/install/var/log/open5gs/pcf.log

sbi:
  server:
    no_tls: true
    cacert: /open5gs/install/etc/open5gs/tls/ca.crt
    key: /open5gs/install/etc/open5gs/tls/pcf.key
    cert: /open5gs/install/etc/open5gs/tls/pcf.crt
  client:
    no_tls: true
    cacert: /open5gs/install/etc/open5gs/tls/ca.crt
    key: /open5gs/install/etc/open5gs/tls/pcf.key
    cert: /open5gs/install/etc/open5gs/tls/pcf.crt

pcf:
  sbi:
    - addr: 127.0.0.13
      port: 7777
  metrics:
    - addr: 127.0.0.13
      port: 9090

scp:
  sbi:
    - addr: 127.0.1.10
      port: 7777