logger:
  file: /open5gs/install/var/log/open5gs/smf.log

sbi:
  server:
    no_tls: true
    cacert: /open5gs/install/etc/open5gs/tls/ca.crt
    key: /open5gs/install/etc/open5gs/tls/smf.key
    cert: /open5gs/install/etc/open5gs/tls/smf.crt
  client:
    no_tls: true
    cacert: /open5gs/install/etc/open5gs/tls/ca.crt
    key: /open5gs/install/etc/open5gs/tls/smf.key
    cert: /open5gs/install/etc/open5gs/tls/smf.crt

smf:
  sbi:
    - addr: 127.0.0.4
      port: 7777
  pfcp:
    - addr: 127.0.0.4
  gtpc:
    - addr: 127.0.0.4
  gtpu:
    - addr: 127.0.0.4
  metrics:
    - addr: 127.0.0.4
      port: 9090
  subnet:
    - addr: 10.45.0.1/16
  dns:
    - 8.8.8.8
    - 8.8.4.4
  mtu: 1400
  ctf:
    enabled: auto
  freeDiameter: /open5gs/install/etc/freeDiameter/smf.conf

scp:
  sbi:
    - addr: 127.0.1.10
      port: 7777

upf:
  pfcp:
    - addr: 127.0.0.7