
apiVersion: v1
kind: Service
metadata:
  name: ausf-nausf
  labels:
    app: open5gs
    nf: ausf
spec:
  ports:
    - name: sbi
      port: 7777
    - name: sbi2
      port: 80
  selector:
    app: open5gs
    nf: ausf
