apiVersion: v1
kind: ConfigMap
metadata:
  name: udr-configmap
  labels:
    app: open5gs
data:
  udrcfg.yaml: |
    db_uri: mongodb://mongodb/open5gs

    logger:
      file: /open5gs/install/var/log/open5gs/udr.log
    
    sbi:
      server:
        no_tls: true
        cacert: /open5gs/install/etc/open5gs/tls/ca.crt
        key: /open5gs/install/etc/open5gs/tls/udr.key
        cert: /open5gs/install/etc/open5gs/tls/udr.crt
      client:
        no_tls: true
        cacert: /open5gs/install/etc/open5gs/tls/ca.crt
        key: /open5gs/install/etc/open5gs/tls/udr.key
        cert: /open5gs/install/etc/open5gs/tls/udr.crt

    udr:
      sbi:
        - dev: eth0
          advertise: udr-nudr
          port: 80

    scp:
      sbi:
        - addr: scp-nscp
          port: 80