apiVersion: v1
kind: Service
metadata:
  name: nssf-nnssf
  labels:
    app: open5gs
    nf: nssf
spec:
  ports:
    - name: sbi
      port: 7777
    - name: sbi2
      port: 80
  selector:
    app: open5gs
    nf: nssf
