apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-nssf
  labels:
    app: open5gs
    nf: nssf
spec:
  selector:
    matchLabels:
      app: open5gs
      nf: nssf
  replicas: 1
  template:
    metadata:
      labels:
        app: open5gs
        nf: nssf
    spec:
      # initContainers:
      # - name: wait-nrf
      #   image: appropriate/curl
      #   command: ['sh', '-c', 'until curl -s -o /dev/null -w "%{http_code}" http://nrf-nnrf:8000 | grep "200"; do sleep 1; done;']
      containers:
      - image: ghcr.io/niloysh/open5gs:v2.6.4-aio
        imagePullPolicy: IfNotPresent
        name: nssf
        ports:
        - containerPort: 7777
        command: ["./open5gs-nssfd"]
        args: ["-c", "/open5gs/config/nssfcfg.yaml"]   
        env:
          - name: GIN_MODE
            value: release
        volumeMounts:
        - mountPath: /open5gs/config/
          name: nssf-volume
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: nssf-volume
        projected:
          sources:
          - configMap:
              name: nssf-configmap
