apiVersion: v1
kind: ConfigMap
metadata:
  name: nssf-configmap
  labels:
    app: open5gs
data:
  nssfcfg.yaml: |
    logger:
      file: /open5gs/install/var/log/open5gs/nssf.log
    
    sbi:
      server:
        no_tls: true
        cacert: /open5gs/install/etc/open5gs/tls/ca.crt
        key: /open5gs/install/etc/open5gs/tls/nssf.key
        cert: /open5gs/install/etc/open5gs/tls/nssf.crt
      client:
        no_tls: true
        cacert: /open5gs/install/etc/open5gs/tls/ca.crt
        key: /open5gs/install/etc/open5gs/tls/nssf.key
        cert: /open5gs/install/etc/open5gs/tls/nssf.crt

    nssf:
      sbi:
        - dev: eth0
          advertise: nssf-nnssf
          port: 80
      nsi:
        - addr: nrf-nnrf
          port: 7777
          s_nssai:
            sst: 1
            sd: 000001
        - addr: nrf-nnrf
          port: 7777
          s_nssai:
            sst: 2
            sd: 000002
          
    scp:
      sbi:
        - addr: scp-nscp
          port: 7777