apiVersion: v1
kind: Service
metadata:
  name: webui-service
  labels:
    app: open5gs
    nf: webui
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 30300
  selector:
    app: open5gs
    nf: webui
