apiVersion: v1
kind: Service
metadata:
  name: amf-namf
  labels:
    app: open5gs
    nf: amf
spec:
  ports:
    - name: sbi
      port: 7777
    - name: metrics
      port: 9000
    - name: sbi2
      port: 80
  selector:
    app: open5gs
    nf: amf
