---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ueransim-ue3
  labels:
    app: ueransim
    component: ue
    name: ue3
spec:
  selector:
    matchLabels:
      app: ueransim
      component: ue
      name: ue3
  replicas: 1
  template:
    metadata:
      labels:
        app: ueransim
        component: ue
        name: ue3
    spec:
      containers:
        - image: ghcr.io/niloysh/ueransim:v3.2.6
          imagePullPolicy: Always
          name: ue
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          # command: [ "/bin/bash", "-c", "--" ]
          # args: [ "while true; do sleep 30; done;" ]
          command: ["/ueransim/config/wrapper.sh"]
          volumeMounts:
            - mountPath: /ueransim/config
              name: ue-volume
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - name: ue-volume
          configMap:
            name: ue3-configmap
            items:
              - key: ue3.yaml
                path: ue3.yaml
              - key: wrapper.sh
                path: wrapper.sh
                mode: 0755
