apiVersion: v1
kind: Service
metadata:
  name: aio-naio
  labels:
    app: open5gs
    nf: aio
spec:
  ports:
    - name: metrics
      port: 9090
  selector:
    app: open5gs
    nf: aio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-aio
  labels:
    app: open5gs
    nf: aio
    name: aio
spec:
  selector:
    matchLabels:
      app: open5gs
      nf: aio
      name: aio
  replicas: 1
  template:
    metadata:
      labels:
        app: open5gs
        nf: aio
        name: aio
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
          { "name": "n2network", "interface": "n2", "ips": [ "10.10.2.1/24" ] },
          { "name": "n3network", "interface": "n3", "ips": [ "10.10.3.1/24" ] },
          { "name": "n4network", "interface": "n4", "ips": [ "10.10.4.1/24" ] }
          ]'
    spec:
      containers:
      - name: aio
        image: ghcr.io/niloysh/open5gs:v2.6.4-aio
        imagePullPolicy: Always
        command: [ "/open5gs/config/init.sh" ]
        env:
        - name: DEBUG_MODE
          value: "true"
        - name: CONFIG_PATH
          value: "/open5gs/config"
        volumeMounts:
        - mountPath: /open5gs/config/
          name: aio-volume
        ports:
        - name: n2
          containerPort: 38412
          protocol: SCTP
        - name: n3
          containerPort: 2152
          protocol: UDP
        - name: n4
          containerPort: 8805
          protocol: UDP
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        securityContext:
          privileged: true
      restartPolicy: Always
      volumes:
      - name: aio-volume
        configMap:
          name: aio-configmap
          defaultMode: 0744
