apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-smf1
  labels:
    app: open5gs
    nf: smf1
    name: smf1
spec:
  selector:
    matchLabels:
      app: open5gs
      nf: smf1
      name: smf1
  replicas: 1
  template:
    metadata:
      labels:
        app: open5gs
        nf: smf1
        name: smf1
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
          { "name": "n3network", "interface": "n3", "ips": [ "10.10.3.11/24" ] },
          { "name": "n4network", "interface": "n4", "ips": [ "10.10.4.11/24" ] }
          ]'
    spec:
      nodeSelector:
        kubernetes.io/hostname: cn231
      containers:
      - image: ghcr.io/niloysh/open5gs:v2.6.4-aio
        name: smf
        imagePullPolicy: IfNotPresent
        ports:
        - name: nsmf
          containerPort: 7777
        - name: pfcp
          containerPort: 8805
          protocol: UDP
        command: ["./open5gs-smfd"]
        args: ["-c", "/open5gs/config/smfcfg.yaml"]   
        env:
          - name: GIN_MODE
            value: release
        volumeMounts:
        - mountPath: /open5gs/config/
          name: smf-volume
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: smf-volume
        projected:
          sources:
          - configMap:
              name: smf1-configmap
              items:
              - key: smfcfg.yaml
                path: smfcfg.yaml