apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- gnb-deployment.yaml
- gnb-service.yaml

configMapGenerator:
  - name: gnb-configmap
    files:
      - config/open5gs-gnb.yaml
      - config/wrapper.sh