apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../open5gs
  - slices

patches:
  - path: patches/pcf-deployment.yaml

configMapGenerator:
- name: amf-configmap
  behavior: replace
  files:
    - patches/amfcfg.yaml

- name: nssf-configmap
  behavior: replace
  files:
    - patches/nssfcfg.yaml

images:
- name: ghcr.io/niloysh/open5gs
  newTag: v2.6.6-upf-metrics-by-seid