apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../ueransim-ue

patches:
  - patch: |-
      kind: not-important
      metadata:
        name: not-important
      spec:
        template:
          spec:
            nodeSelector:
              kubernetes.io/hostname: nuc2
            containers:
              - name: ue
                resources:
                  requests:
                    memory: "100Mi"
                    cpu: "100m"
                  limits:
                    memory: "200Mi"
                    cpu: "200m"

    target:
      kind: Deployment
